### ISSUE TITLE
Running test files fails with this code

### ISSUE THREAD

**Issue by brinaluvsrocks** [Peter-E-Martin/HeFTy_GOFplotter#2]
Python 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
print('hello world')
hello world

= RESTART: /Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py
Traceback (most recent call last):
  File "/Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py", line 20, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
pip install matplotlib
SyntaxError: invalid syntax
import matplotlib

= RESTART: /Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py
Traceback (most recent call last):
  File "/Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py", line 25, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

= RESTART: /Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py
Traceback (most recent call last):
  File "/Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py", line 26, in <module>
    from scipy.stats import combine_pvalues
ModuleNotFoundError: No module named 'scipy'

= RESTART: /Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py
Traceback (most recent call last):
  File "/Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py", line 60, in <module>
    header = pd.read_csv(file,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1250, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 817, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 20 fields in line 2, saw 21

= RESTART: /Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py
Traceback (most recent call last):
  File "/Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py", line 60, in <module>
    header = pd.read_csv(file,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1250, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 817, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 20 fields in line 2, saw 21

= RESTART: /Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py
Traceback (most recent call last):
  File "/Users/sabrinakainz/Downloads/HeFTy_GOFplotter-main/HeFTy_plotter.py", line 60, in <module>
    header = pd.read_csv(file,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1250, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 817, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 20 fields in line 2, saw 77

**Comment by Peter-E-Martin** [comment]
This appears to be due to an update to panda's read_csv function, which does not handle varying row lengths well. I'm pushing a new commit to deal with this now.
