### ISSUE TITLE
Using HeFTy files with no 'good' fits doesn't run 

### ISSUE THREAD

**Issue by brinaluvsrocks** [Peter-E-Martin/HeFTy_GOFplotter#3]
Python 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: /Users/sabrinakainz/Desktop/Honours Thesis/HeFTy/HeFTy_GOFplotter-main/HeFTy_GOFplotter-main/HeFTy_plotter.py
Traceback (most recent call last):
  File "/Users/sabrinakainz/Desktop/Honours Thesis/HeFTy/HeFTy_GOFplotter-main/HeFTy_GOFplotter-main/HeFTy_plotter.py", line 132, in <module>
    good_idx = list(np.delete(good_idx, best_idx))
  File "<__array_function__ internals>", line 180, in delete
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5099, in delete
    raise IndexError(
IndexError: index 267 is out of bounds for axis 0 with size 0

**Comment by Peter-E-Martin** [comment]
This issue was due to leaving the ```good_vs_acceptable``` variable set to ```True``` when no good fits were present. The code now makes sure that good fits are present first, and skips the step causing an error if none are present.
